/**
 * Build a BibTeX entry for one included paper. Tries to use the
 * paper's externalDoi or externalArxivId when present; falls back to
 * a generic `@misc` shape with whatever URL / source info exists.
 *
 * The citation key matches the draft's `[paper_id]` style so a
 * researcher can search-and-replace the key into LaTeX manuscripts
 * directly. Keys are sanitised to BibTeX's allowed character set
 * (alphanumeric + `-_:`).
 */
export type BibTexPaper = {
  /** Stable id used in the draft as `[paper_XXX]`. */
  citationKey: string;
  /** Falls back to "Untitled paper" when missing — BibTeX requires SOMETHING. */
  title: string | null;
  /** Cross-reference; one or both may be null. */
  externalDoi: string | null;
  externalArxivId: string | null;
  /** R2 blob key for uploaded items, e.g. "corpus/<projectId>/<uuid>.pdf". */
  source: string | null;
};

/**
 * BibTeX values escape backslashes + braces + the `@` symbol. The
 * canonical character to wrap in is `{}`, which lets nearly any
 * content through unescaped.
 */
function bibtexEscape(value: string): string {
  return value.replace(/[\\{}@]/g, (m) => `\\${m}`);
}

function sanitiseKey(key: string): string {
  // BibTeX citation keys allow alphanumeric + `-_:.` in most engines
  // (biber + biblatex + bibtex). Replace anything outside that set
  // (e.g. forward slashes in DOIs) with `_` so a key like `10.1/foo`
  // becomes `10.1_foo`. Dots stay so DOI-shaped keys remain
  // recognisable.
  return key.replace(/[^A-Za-z0-9\-_:.]/g, "_") || "untitled";
}

export function paperToBibtex(p: BibTexPaper): string {
  const key = sanitiseKey(p.citationKey);
  const title = bibtexEscape(p.title ?? "Untitled paper");

  // Prefer @article when there's a DOI (a published paper). Otherwise
  // @misc which is the BibTeX catch-all for arXiv preprints + grey
  // literature.
  const entryType = p.externalDoi ? "article" : "misc";

  const fields: string[] = [`  title = {${title}}`];
  if (p.externalDoi) {
    fields.push(`  doi = {${bibtexEscape(p.externalDoi)}}`);
    fields.push(`  url = {https://doi.org/${bibtexEscape(p.externalDoi)}}`);
  }
  if (p.externalArxivId) {
    fields.push(`  eprint = {${bibtexEscape(p.externalArxivId)}}`);
    fields.push(`  archivePrefix = {arXiv}`);
    if (!p.externalDoi) {
      fields.push(`  url = {https://arxiv.org/abs/${bibtexEscape(p.externalArxivId)}}`);
    }
  }
  if (!p.externalDoi && !p.externalArxivId && p.source) {
    // Uploaded PDFs with no DOI/arxiv id — capture the source path so
    // the citation isn't dangling.
    fields.push(`  note = {Uploaded PDF: ${bibtexEscape(p.source)}}`);
  }

  return `@${entryType}{${key},\n${fields.join(",\n")},\n}`;
}

export function buildBibtexFile(papers: BibTexPaper[]): string {
  if (papers.length === 0) {
    return "% No papers included in this review.\n";
  }
  const header = "% Generated by Thoth (https://thoth-slr.vercel.app).\n";
  return header + papers.map(paperToBibtex).join("\n\n") + "\n";
}
