import { NextRequest, NextResponse } from "next/server";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { buildRunFilename } from "@/lib/download-filename";

/**
 * Download a completed Run's draft as a Markdown file.
 *
 * Returns 404 for "no such run", "not yours", or "no draft yet" — same
 * existence-probe defense as the rest of the API.
 *
 * Filename includes a slug of the project title + the run's date
 * (YYYY-MM-DD) so multiple downloads sort sensibly in Downloads:
 * `thoth-archaeal-hibernation-2026-05-28.md`.
 */
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const user = await requireUser().catch(() => null);
  if (!user) return new NextResponse("Unauthorized", { status: 401 });

  const { id } = await params;
  const run = await db.run.findUnique({
    where: { id },
    select: {
      draft: true,
      createdAt: true,
      project: { select: { ownerId: true, title: true } },
    },
  });
  if (!run || run.project.ownerId !== user.id || !run.draft) {
    return new NextResponse("Not found", { status: 404 });
  }

  const filename = buildRunFilename({
    projectTitle: run.project.title,
    runId: id,
    startedAt: run.createdAt,
    suffix: "md",
  });

  return new NextResponse(run.draft, {
    status: 200,
    headers: {
      "content-type": "text/markdown; charset=utf-8",
      "content-disposition": `attachment; filename="${filename}"`,
      // Don't cache — the draft can be regenerated by a follow-up run,
      // and stale downloads would be misleading.
      "cache-control": "no-store",
    },
  });
}
